version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:183650099165:task-definition/TaskDefinitionDEMO:30"
        LoadBalancerInfo: 
          ContainerName: "httpdDEMO"
          ContainerPort: 80