version: 0.2
#run-as: codebuild-user
run-as: root
phases:
  install:
    commands:
#      - yum install docker -y
#      - systemctl start docker
#      - service docker.io start
      - echo 'in install'
#      - apt install rpl
#      - dockerd
#      - service docker.io start
      - apt-get update
      - apt-get install rpl
#      - apt-get install docker-ce docker-ce-cli containerd.io
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 183650099165.dkr.ecr.ap-south-1.amazonaws.com
      - docker build -t dockerdemo .
      - docker tag dockerdemo:latest 183650099165.dkr.ecr.ap-south-1.amazonaws.com/dockerdemo:latest
      - docker push 183650099165.dkr.ecr.ap-south-1.amazonaws.com/dockerdemo:latest
      - echo 'in install phase'
      - echo 'in pre build phase'
    finally:
      - echo 'in finally of prebuild phase'
      - OUTPUT=$(aws ecs describe-task-definition --task-definition TaskDefinitionDEMO | jq '.[] | .taskDefinitionArn')
      - rpl '$task_def' ${OUTPUT} appspec.yaml
  build:
    commands:
      - cat appspec.yaml
      - echo 'in build phase'
      - ls -la
  post_build:
    run-as: root
    commands:
      - whoami
      - echo 'in post build phase'
    finally:
      - ls -la
      - cat index.html

artifacts:
  files:
    - '**/*'
#    base-directory: 'docker'
